drop database ivblanc;
select @@global.transaction_isolation, @@transaction_isolation;
set @@transaction_isolation="read-committed";
SET GLOBAL time_zone='+09:00';
SET time_zone='+09:00';
create database ivblanc;
use ivblanc;
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
	`user_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`email`	VARCHAR(255)	NOT NULL,
	`password`	VARCHAR(15)	NOT NULL,
	`name`	VARCHAR(20)	NOT NULL,
	`age`	INT	NULL,
	`gender`	INT	NULL,
	`phone`	VARCHAR(15)	NULL,
	`social`	INT	NULL
);

DROP TABLE IF EXISTS `STYLE`;

CREATE TABLE `STYLE` (
	`style_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`madeby`	VARCHAR(20)	NOT NULL,
	`favorite`	INT	default 0,
	`url`	VARCHAR(2000)	NULL,
	`photo_name`	VARCHAR(255)	NULL,
	`user_id`	INT	NOT NULL
);

DROP TABLE IF EXISTS `STYLE_DETAIL`;

CREATE TABLE `STYLE_DETAIL` (
	`sd_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`style_id`	INT	NOT NULL,
	`clothes_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL
);

DROP TABLE IF EXISTS `HISTORY`;

CREATE TABLE `HISTORY` (
	`history_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`location`	decimal(10,7)	NULL,
	`Field`	decimal(11,7)	NULL,
	`date`	timestamp default CURRENT_TIMESTAMP,
	`weather`	VARCHAR(10)	NULL,
	`temperature`	VARCHAR(10)	NULL,
	`text`	VARCHAR(2000)	NULL,
	`subject`	VARCHAR(255)	NULL,
	`styleurl`	VARCHAR(2000)	NULL,
	`user_id`	INT	NOT NULL
);

DROP TABLE IF EXISTS `USER_TOKEN`;

CREATE TABLE `USER_TOKEN` (
	`user_id`	INT	NOT NULL,
	`jwt`	VARCHAR(512)	NULL,
	`fcm`	VARCHAR(512)	NULL,
	`code`	VARCHAR(512)	NULL
);

DROP TABLE IF EXISTS `CLOTHES`;

CREATE TABLE `CLOTHES` (
	`clothes_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`category`	INT	NULL,
	`color`	VARCHAR(8)	NULL,
	`material`	VARCHAR(10)	NULL,
	`date`	timestamp default CURRENT_TIMESTAMP,
	`url`	VARCHAR(2000)	NULL,
	`favorite`	INT	default 0,
	`size`	INT	NULL,
	`season`	INT	NULL,
	`count`	INT	default 0,
	`likepoint`	INT	default 0,
	`dislikepoint`	INT	default 0,
	`user_id`	INT	NOT NULL
);

DROP TABLE IF EXISTS `FRIEND`;

CREATE TABLE `FRIEND` (
	`friend_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`applicant`	VARCHAR(255)	NULL,
	`friend`	VARCHAR(255)	NULL,
	`isaccept`	VARCHAR(1)	default 'N' 
);

DROP TABLE IF EXISTS `PHOTO`;

CREATE TABLE `PHOTO` (
	`photo_id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`url`	VARCHAR(2000)	NULL,
	`diary_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL
);

ALTER TABLE `STYLE` ADD CONSTRAINT `FK_USER_TO_STYLE_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`user_id`
    
)ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `STYLE_DETAIL` ADD CONSTRAINT `FK_STYLE_TO_STYLE_DETAIL_1` FOREIGN KEY (
	`style_id`
)
REFERENCES `STYLE` (
	`style_id`
)ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `STYLE_DETAIL` ADD CONSTRAINT `FK_STYLE_TO_STYLE_DETAIL_2` FOREIGN KEY (
	`user_id`
)
REFERENCES `STYLE` (
	`user_id`
)ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `STYLE_DETAIL` ADD CONSTRAINT `FK_CLOTHES_TO_STYLE_DETAIL_1` FOREIGN KEY (
	`clothes_id`
)
REFERENCES `CLOTHES` (
	`clothes_id`
)ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `HISTORY` ADD CONSTRAINT `FK_USER_TO_HISTORY_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`user_id`
)ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `USER_TOKEN` ADD CONSTRAINT `FK_USER_TO_USER_TOKEN_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`user_id`
) ON UPDATE CASCADE ON DELETE CASCADE; 

ALTER TABLE `CLOTHES` ADD CONSTRAINT `FK_USER_TO_CLOTHES_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`user_id`  
) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `PHOTO` ADD CONSTRAINT `FK_HISTORY_TO_PHOTO_1` FOREIGN KEY (
	`diary_id`
)
REFERENCES `HISTORY` (
	`history_id`
)ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `PHOTO` ADD CONSTRAINT `FK_HISTORY_TO_PHOTO_2` FOREIGN KEY (
	`user_id`
)
REFERENCES `HISTORY` (
	`user_id`
)ON UPDATE CASCADE ON DELETE CASCADE;


